//
//  user.m
//  作业派-教师端
//
//  Created by zero on 2018/4/17.
//  Copyright © 2018年 zero. All rights reserved.
//

#import "user.h"

@implementation user
- (instancetype)initWithName:(NSString *)THIS_TEACHER_USER_NAME
        THIS_TEACHER_USER_ID:(NSString *)THIS_TEACHER_USER_ID
  THIS_TEACHER_USER_PASSWORD:(NSString *)THIS_TEACHER_USER_PASSWORD
  THIS_TEACHER_USER_TOUXIANG:(NSString *)THIS_TEACHER_USER_TOUXIANG
          THIS_USER_IS_LOGIN:(NSString *)THIS_USER_IS_LOGIN
THIS_USER_BOLONG_TO_SCHOOL_ID:(NSString *)THIS_USER_BOLONG_TO_SCHOOL_ID
THIS_USER_BOLONG_TO_SCHOOL_NAME:(NSString *)THIS_USER_BOLONG_TO_SCHOOL_NAME
{
    self = [super init];
    if (self) {
        self.THIS_TEACHER_USER_NAME = THIS_TEACHER_USER_NAME;
        self.THIS_TEACHER_USER_ID=THIS_TEACHER_USER_ID;
        self.THIS_TEACHER_USER_PASSWORD=THIS_TEACHER_USER_PASSWORD;
        self.THIS_TEACHER_USER_TOUXIANG=THIS_TEACHER_USER_TOUXIANG;
        self.THIS_USER_IS_LOGIN=THIS_USER_IS_LOGIN;
        self.THIS_USER_BOLONG_TO_SCHOOL_ID=THIS_USER_BOLONG_TO_SCHOOL_ID;
        self.THIS_USER_BOLONG_TO_SCHOOL_NAME=THIS_USER_BOLONG_TO_SCHOOL_NAME;
    }
    return self;
}
+ (instancetype)UserWithName:(NSString *)THIS_TEACHER_USER_NAME
        THIS_TEACHER_USER_ID:(NSString *)THIS_TEACHER_USER_ID
  THIS_TEACHER_USER_PASSWORD:(NSString *)THIS_TEACHER_USER_PASSWORD
  THIS_TEACHER_USER_TOUXIANG:(NSString *)THIS_TEACHER_USER_TOUXIANG
          THIS_USER_IS_LOGIN:(NSString *)THIS_USER_IS_LOGIN
THIS_USER_BOLONG_TO_SCHOOL_ID:(NSString *)THIS_USER_BOLONG_TO_SCHOOL_ID
THIS_USER_BOLONG_TO_SCHOOL_NAME:(NSString *)THIS_USER_BOLONG_TO_SCHOOL_NAME
{
    return [[user alloc] initWithName:THIS_TEACHER_USER_NAME
                 THIS_TEACHER_USER_ID:THIS_TEACHER_USER_ID
           THIS_TEACHER_USER_PASSWORD:THIS_TEACHER_USER_PASSWORD
           THIS_TEACHER_USER_TOUXIANG:THIS_TEACHER_USER_TOUXIANG
                   THIS_USER_IS_LOGIN:THIS_USER_IS_LOGIN
        THIS_USER_BOLONG_TO_SCHOOL_ID:THIS_USER_BOLONG_TO_SCHOOL_ID
      THIS_USER_BOLONG_TO_SCHOOL_NAME:THIS_USER_BOLONG_TO_SCHOOL_NAME];

}
@end
